spring:
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/example?charSet=UTF8}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
application:
  groupId: 173753932
  serviceKey: a0ba7f69a0ba7f69a0ba7f6920a0dc9331aa0baa0ba7f69fb59b26d9890002a53a6cf04
  id: 6745176
  secret: LQFLwAm8zjBzDaQA9MbC
  storage:
    location: images
