spring:
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/example?charSet=UTF8}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
application:
  groupId: 173753932
  serviceKey: 2d6f23ba2d6f23ba2d6f23ba982d09d26422d6f2d6f23ba768a529ed28d69072e956677
  apiVersion: 5.52
  yandexKey: 74c5a342-8ead-45bf-964e-b94bcce3b472
  id: 6745176
  secret: LQFLwAm8zjBzDaQA9MbC
  storage:
    location: images
